### ISSUE TITLE
Persist session

### ISSUE THREAD

**Issue by ghost** [Rhymmor/tinkoff-api#3]
Is there any way to persist session for later usage like mobile app do?

**Comment by Rhymmor** [comment]
Hi @KirillSaltykov 

I've checked the auth duration on the mobile app right now. Looks like it's the same 10 minutes that we get via REST API. So probably they use it inside the app.

Basically, you can persist session, if your user stays active during these 10 minutes. 
If you've already got `sessionId` via `initializeSession()` call, you can check the status with `checkSessionStatus()` and refresh it with `warmUpCache()`:

```typescript
const sessionId = ...;

let status = await api.checkSessionStatus(sessionId);
// status.payload.millisLeft = 350179  <-  the session has ~6 minutes left

await api.warmUpCache(sessionId);

status = await api.checkSessionStatus(sessionId);
// status.payload.millisLeft = 599796  <-  the session has 10 minutes left again
```
